import type { Metadata } from "next";

// Removing remote Google font imports to avoid build-time network requests.
// If you would like to use custom fonts, consider bundling them locally with
// `next/font/local` instead of `next/font/google`, which fetches assets at
// build-time and fails in network-restricted environments (like CI).

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Remove font variables that depended on Google fonts */}
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
